In [5]:
# 🧪 텐서 기초 실습 - PyTorch

import torch


In [7]:

# 1차원 텐서 생성
a = torch.tensor([1.0, 2.0, 3.0])
print("1D Tensor:", a)


1D Tensor: tensor([1., 2., 3.])


In [8]:

# 2차원 텐서 (행렬) 생성
b = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor:\n", b)


2D Tensor:
 tensor([[1, 2],
        [3, 4]])


In [9]:

# 텐서의 형태(shape)
print("Shape of b:", b.shape)


Shape of b: torch.Size([2, 2])


In [10]:

# 0~1 사이 랜덤값 텐서
c = torch.rand(2, 3)
print("Random Tensor:\n", c)


Random Tensor:
 tensor([[0.7313, 0.7501, 0.8349],
        [0.6566, 0.6046, 0.6279]])


In [11]:

# 텐서 타입 변경
d = c.int()
print("Changed to int:\n", d)


Changed to int:
 tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [12]:

# 텐서 연산 (덧셈, 곱셈)
x = torch.tensor([1.0, 2.0])
y = torch.tensor([3.0, 4.0])
print("덧셈:", x + y)
print("곱셈:", x * y)  # 원소별 곱


덧셈: tensor([4., 6.])
곱셈: tensor([3., 8.])


In [ ]:

# 행렬 곱 (dot product)
# 행렬 곱 조건: 앞 행렬의 열 수 == 뒤 행렬의 행 수
z = torch.matmul(torch.tensor([[1, 2]]), torch.tensor([[3], [4]]))
print("행렬 곱 결과:", z)


행렬 곱 결과: tensor([[11]])
